
// SESSION MODULE
export const DEFINE_SESSION = 'DEFINE_SESSION'


// BATTLES MODULE
export const DEFINE_BATTLES       = 'DEFINE_BATTLES'
export const DEFINE_ACTIVE_BATTLE = 'DEFINE_ACTIVE_BATTLE'


// USERS MODULE
export const DEFINE_USERS    = 'DEFINE_USERS'
export const ADD_USER_OBJ    = 'ADD_USER_OBJ'
export const REMOVE_USER_OBJ = 'REMOVE_USER_OBJ'


// LOTTERY MODULE
export const DEFINE_SELECTED_USERS = 'DEFINE_SELECTED_USERS'
export const DEFINE_NAME           = 'DEFINE_NAME'
export const DEFINE_DESCRIPTION    = 'DEFINE_DESCRIPTION'
export const DEFINE_FILTERED_USERS = 'DEFINE_FILTERED_USERS'
